version: '3'

services:
  emusic-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - emusicappnet

    
  emusic-api:
    restart: unless-stopped
    build: .
    environment:
      - ConnectionStrings:eMusic=Server=emusic-sql,1433;Database=eMusicDocker;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 61967:5050
    networks:
      - emusicappnet     
    links:
      - emusic-sql
    depends_on:
      - emusic-sql
      
networks:
  emusicappnet:
    driver: bridge

        